### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by ohlawdie** [ioncodes/beeless#2]
Hi Luca, I am new to programming recon. How does this work? Do I need to implement it into de4dot somehow? I'm not sure if I am just supposed to drop the Beeless folder into the de4dot.code/deobfuscators section or not and I have the required files for dnlib (so I think). 

Any help would be much obliged, thank you.
Evan

**Comment by ioncodes** [comment]
Sorry for the late reply! You just download the project, compile it and then you call ```beeless.exe <file>```. It has nothing to do with de4dot, but de4dot works as well for deobfuscation of BeeByte obfuscated binaries. Let me know if something isn't working!

**Comment by ohlawdie** [comment]
No problem, thanks a lot! I'm going to try that later today :).

**Comment by ohlawdie** [comment]
For some reason I was unable to get De4Dot to work with Beeless - which is fine, because I got your solution to compile! I was just missing a reference to dnlib.dll that doesn't come with your repo but I had an extra copy of the library lying around. Thanks again!

**Comment by ioncodes** [comment]
No problem! de4dot should be better than beeless tho, this project just demangles the names, nothing special. BB doesn't have any control flow obfuscation afaik, but I might be wrong. If that's the case you should definitely use de4dot instead. You can also make your own deobfuscator with dnpatch (https://github.com/ioncodes/dnpatch), just keep in mind that the v1 branch isn't 100% done yet, so you may want to stick with the current final (master branch).
