### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by NotIllu** [ioncodes/beeless#3]
Hay, used Beeless but I cant find any difference between the normal DLL and the cleaned one.
Used it with beeless.exe <filename in same directory>.
Compiled everything myself just used .net 4.6.1 instead of the one original used ( I hope thats not the problem ), so I'm basicly still stuck with this https://i.imgur.com/8P2LvQD.png

thanks in advance for pointing me in the right direction,

PS: tbh I'm new to this stuff, so maybe I expected more then possible. Also I dont know if its Beebyte for sure but some strings  like "__BB_OBFUSCATION_1_2_6__" indicate that.

**Comment by ioncodes** [comment]
Try using de4dot and show me if it's different.

**Comment by ioncodes** [comment]
de4dot may be better for BB anyways, what beeless does is normalize the names, I'm not sure if there's also control flow obfuscation, but there isn't afaik.

**Comment by ioncodes** [comment]
I'll def have a look at it tmrw tho, if you have Discord you can reach out to me at ion#1387
